# Generated by Django 4.2 on 2023-04-27 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docs',
            old_name='data',
            new_name='files',
        ),
    ]
