# Generated by Django 4.2.2 on 2023-06-30 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_categoryarticle_rubriquemagazine_article_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazine',
            name='docs',
        ),
        migrations.AddField(
            model_name='docs',
            name='magazine',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='articles.magazine'),
            preserve_default=False,
        ),
    ]
