# Generated by Django 4.2.2 on 2023-06-30 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_remove_magazine_docs_docs_magazine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docs',
            name='magazine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='articles.magazine'),
        ),
    ]
